### ISSUE TITLE
Profile management (CRUD) for Patients

### ISSUE THREAD

**Issue by PedroNuno22** [PedroNuno22/ARQSI-24-25#3]
•	Develop the interface for Admins to create, update, and manage patient profiles.
•	Implement GDPR-compliant account deletion for patients.

User Stories:

	•	5.1.8: “As an Admin, I want to create a new patient profile, so that I can register their personal details and medical history.”
	•	5.1.9: “As an Admin, I want to edit an existing patient profile, so that I can update their information when needed.”
	•	5.1.10: “As an Admin, I want to delete a patient profile, so that I can remove patients who are no longer under care.”
	•	5.1.11: “As an Admin, I want to list/search patient profiles by different attributes, so that I can view the details, edit, and remove patient profiles.”
	•	5.1.5: “As a Patient, I want to delete my account and all associated data, so that I can exercise my right to be forgotten as per GDPR.”

**Comment by guedes2310** [comment]
Neste momento, as operações CRUD estão a funcionar faltando o ponto 5.1.5: “As a Patient, I want to delete my account and all associated data, so that I can exercise my right to be forgotten as per GDPR.” . Penso que deveria ser associado ao "operation self-registration pacient", tema de discussão para weekly meeting.
